export ROOT_MODULE_PATH=$ROOT_MODULE_PATH:$PWD/build
export ROOT_INCLUDE_PATH=$ROOT_INCLUDE_PATH:$PWD/interface
export ROOT_LIBRARY_PATH=$ROOT_INCLUDE_PATH:$PWD/build
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/build
export PYTHONPATH=$PYTHONPATH:$PWD/python

